import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs'
import { Database } from '@/models/supabase'
import Navbar from './components/navbar'

const inter = Inter({ subsets: ['latin'] })
const supabase = createClientComponentClient<Database>()

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
